name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push to Docker Hub
      run: |
        cd app
        docker build -t ${{ secrets.DOCKER_USERNAME }}/xplore-travels:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/xplore-travels:latest

    - name: Deploy to EC2
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
        chmod 600 key.pem
        
        ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -i key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          echo "Pulling latest image..."
          docker pull ${{ secrets.DOCKER_USERNAME }}/xplore-travels:latest
          
          echo "Stopping existing container..."
          docker stop xplore-travels || true
          docker rm xplore-travels || true
          
          echo "Starting new container..."
          docker run -d --name xplore-travels -p 5000:5000 --restart unless-stopped ${{ secrets.DOCKER_USERNAME }}/xplore-travels:latest
          
          echo "Cleaning up old images..."
          docker image prune -f
          
          echo "Deployment completed successfully!"
          docker ps | grep xplore-travels
        EOF
        
